src/Entity/Credit.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use App\Repository\CreditRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=CreditRepository::class)
 */
class Credit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $designation;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant_min;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant_max;

    /**
     * @ORM\Column(type="float")
     */
    private $taux;

    /**
     * @ORM\ManyToMany(targetEntity=Duree::class, inversedBy="credits")
     * @OrderBy({"mensualite" = "ASC"})
     */
    private $mensualites;

    public function __construct()
    {
        $this->mensualites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getMontantMin(): ?int
    {
        return $this->montant_min;
    }

    public function setMontantMin(int $montant_min): self
    {
        $this->montant_min = $montant_min;

        return $this;
    }

    public function getMontantMax(): ?int
    {
        return $this->montant_max;
    }

    public function setMontantMax(int $montant_max): self
    {
        $this->montant_max = $montant_max;

        return $this;
    }

    public function getTaux(): ?float
    {
        return $this->taux;
    }

    public function setTaux(float $taux): self
    {
        $this->taux = $taux;

        return $this;
    }

    public function __toString()
    {
        return $this->designation;
    }

    /**
     * @return Collection|Duree[]
     */
    public function getMensualites(): Collection
    {
        return $this->mensualites;
    }

    public function addMensualite(Duree $mensualite): self
    {
        if (!$this->mensualites->contains($mensualite)) {
            $this->mensualites[] = $mensualite;
        }

        return $this;
    }

    public function removeMensualite(Duree $mensualite): self
    {
        $this->mensualites->removeElement($mensualite);

        return $this;
    }
}

src/Form/CreditType.php
<?php

namespace App\Form;

use App\Entity\Duree;
use App\Entity\Credit;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class CreditType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('designation')
            ->add('actif')
            ->add('montant_min')
            ->add('montant_max')
            ->add('taux', NumberType::class, [
                'scale' => 4,
            ])
            ->add('mensualites', EntityType::class, [
                'class' => Duree::class,
                'choice_label' => 'mensualite',
                'multiple' => true,
                'expanded' => true, 
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.mensualite', 'ASC');
                },
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Credit::class,
        ]);
    }
}

src/Controller/CreditController.php
<?php

namespace App\Controller;

use App\Entity\Duree;
use App\Entity\Credit;
use App\Form\CreditType;
use App\Form\Credit1Type;
use App\Repository\CreditRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/credit')]
/**
 * @Route("/")
 */
class CreditController extends AbstractController
{
    #[Route('/', name: 'credit_index', methods: ['GET'])]
    public function index(CreditRepository $creditRepository): Response
    {

        return $this->render('credit/index.html.twig', [
            'credits' => $creditRepository->findByAscendantField(),
        ]);
    }

    #[Route('/new', name: 'credit_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $credit = new Credit();
        $form = $this->createForm(CreditType::class, $credit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($credit);
            $entityManager->flush();

            return $this->redirectToRoute('credit_index');
        }

        return $this->render('credit/new.html.twig', [
            'credit' => $credit,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'credit_show', methods: ['GET'])]
    public function show(Credit $credit): Response
    {
        return $this->render('credit/show.html.twig', [
            'credit' => $credit,
        ]);
    }

    #[Route('/{id}/edit', name: 'credit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Credit $credit): Response
    {
        $form = $this->createForm(CreditType::class, $credit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('credit_index');
        }

        return $this->render('credit/edit.html.twig', [
            'credit' => $credit,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/{id}', name: 'credit_delete', methods: ['POST'])]
    public function delete(Request $request, Credit $credit): Response
    {
        if ($this->isCsrfTokenValid('delete'.$credit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($credit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('credit_index');
    }
}

templates/credit/_delete_form.html.twig
<form method="post" action="{{ path('credit_delete', {'id': credit.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer cet élément?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ credit.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/credit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/credit/edit.html.twig
{% extends 'admin_base.html.twig' %}

{% block title %}Editer Crédit{% endblock %}

{% block body %}

    <div id="container-main">

        <div class="menu">
        
        
            <a href="{{ path('credit_index') }}">Revenir à la liste</a>
        
        
        </div>

        <div class="content">
        
            <h1>Editer un crédit</h1>
            
            {{ include('credit/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
            
            {{ include('credit/_delete_form.html.twig') }}
        
        </div>

       
    </div>
    
{% endblock %}

templates/credit/index.html.twig
{% extends 'admin_base.html.twig' %}

{% block title %}Credits{% endblock %}

{% block body %}

    <div id="container-main">

        <div class="menu mt-4">
        
            <a href="{{ path('credit_new') }}">Creer un nouveau crédit</a>
        
        </div>

        <div class="content mt-4">
        
            <h1>Credits</h1>

            <table class="table">
                <thead>
                    <tr>
                        <th>Designation</th>
                        <th>Actif</th>
                        <th>Montant_min</th>
                        <th>Montant_max</th>
                        <th>Taux</th>
                        <th>actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for credit in credits %}
                    <tr>
                        <td>{{ credit.designation }}</td>
                        <td>{{ credit.actif ? 'Yes' : 'No' }}</td>
                        <td>{{ credit.montantMin }}</td>
                        <td>{{ credit.montantMax }}</td>
                        <td>{{ credit.taux }}</td>
                        <td>
                            <a href="{{ path('credit_show', {'id': credit.id}) }}">Détail</a> |
                            <a href="{{ path('credit_edit', {'id': credit.id}) }}">Editer</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="6">Aucun crédit enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        
        </div>

    </div>
    
{% endblock %}

templates/credit/new.html.twig
{% extends 'admin_base.html.twig' %}

{% block title %}Nouveau crédit{% endblock %}

{% block body %}

<div id="container-main">

        <div class="menu">
        
             <a href="{{ path('credit_index') }}">revenir à la liste</a>
        
        </div>

        <div class="content">
        
            <h1>Créer un nouveau crédit</h1>

            {{ include('credit/_form.html.twig') }}
        
        </div>

</div>
    
{% endblock %}

templates/credit/show.html.twig
{% extends 'admin_base.html.twig' %}

{% block title %}Credit{% endblock %}

{% block body %}

    <div id="container-main">

        <div class="menu">
        
            <a href="{{ path('credit_index') }}">revenir à la liste</a>

            <a href="{{ path('credit_edit', {'id': credit.id}) }}">éditer</a>
        
        </div>

        <div class="content">
        
            <h1>Credit</h1>

            <table class="table">
                <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ credit.id }}</td>
                    </tr>
                    <tr>
                        <th>Designation</th>
                        <td>{{ credit.designation }}</td>
                    </tr>
                    <tr>
                        <th>Actif</th>
                        <td>{{ credit.actif ? 'Yes' : 'No' }}</td>
                    </tr>
                    <tr>
                        <th>Montant_min</th>
                        <td>{{ credit.montantMin }}</td>
                    </tr>
                    <tr>
                        <th>Montant_max</th>
                        <td>{{ credit.montantMax }}</td>
                    </tr>
                    <tr>
                        <th>Taux</th>
                        <td>{{ credit.taux }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        {{ include('credit/_delete_form.html.twig') }}

    </div>
    
{% endblock %}